### ISSUE TITLE
preprocessing error

### ISSUE THREAD

**Issue by shizukadara** [hulianyuyy/CorrNet#33]
I am trying to preprocess the data with "!python dataset_preprocess-T.py --process-image --multiprocessing"
but this is the error it gives. I have created the symbolic link properly and verified it too (!ln -s /mnt/c/Users/Samriddha\ Sanyal/PHOENIX-2014-T-release-v3/PHOENIX-2014-T ./dataset/phoenix2014-T)
 I have referred to this  #10 and moved the files in the features folders into a new "1" subdirectory by executing the script for dev and test although not yet for train. 

I am working with phoenix2014-T dataset

`Traceback (most recent call last):
  File "/mnt/c/Users/Samriddha Sanyal/Corrnet-main/preprocess/dataset_preprocess-T.py", line 109, in <module>
    information = csv2dict(f"{args.dataset_root}/{args.annotation_prefix.format(md)}", dataset_type=md)
  File "/mnt/c/Users/Samriddha Sanyal/Corrnet-main/preprocess/dataset_preprocess-T.py", line 15, in csv2dict
    inputs_list = pandas.read_csv(anno_path)
  File "/home/shizuka/anaconda3/envs/corrnet2/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/shizuka/anaconda3/envs/corrnet2/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/shizuka/anaconda3/envs/corrnet2/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/shizuka/anaconda3/envs/corrnet2/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/shizuka/anaconda3/envs/corrnet2/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/shizuka/anaconda3/envs/corrnet2/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/shizuka/anaconda3/envs/corrnet2/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/shizuka/anaconda3/envs/corrnet2/lib/python3.9/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/disk1/dataset/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/annotations/manual/PHOENIX-2014-T.dev.corpus.csv'`

**Comment by hulianyuyy** [comment]
It seems that you should modify the 'dataset-root' hyperparameter in the dataset_preprocess-T.py as you want.

**Comment by Uily1YUT** [comment]
你好，我也是在预处理出现错误，(corrnet) root@autodl-container-e03342a261-0551d25e:~/autodl-fs/CorrNet-main/preprocess# python dataset_preprocess-T.py --process-image --multiprocessing
Generate information dict from /root/autodl-fs/phoenix-14T/annotations/manual/PHOENIX-2014-T.dev.corpus.csv
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 519/519 [00:00<00:00, 1089.46it/s]
Resize image to 256x256px
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 519/519 [05:20<00:00,  1.62it/s]
Generate information dict from /root/autodl-fs/phoenix-14T/annotations/manual/PHOENIX-2014-T.test.corpus.csv
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 642/642 [00:00<00:00, 2395.72it/s]
Resize image to 256x256px
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 642/642 [01:07<00:00,  9.50it/s]
Traceback (most recent call last):
  File "dataset_preprocess-T.py", line 133, in <module>
    information = csv2dict(f"{args.dataset_root}/{args.annotation_prefix.format(md)}", dataset_type=md,
  File "dataset_preprocess-T.py", line 29, in csv2dict
    inputs_list = (inputs_list.to_dict()['name|video|start|end|speaker|orth|translation'].values())
KeyError: 'name|video|start|end|speaker|orth|translation'
是在train文件夹出现的错误，据我搜索得到是UTF-8编码的错误，于是我尝试换编码，最后验证 ISO-8859-1编码时，train正常运行，但是dev和test有大量错误，接着我试着让dev和test使用UTF-8编码，train使用 ISO-8859-1编码，但是出现了最开始使用UTF-8时一模一样的错误。我想知道你的文件编码是什么？感谢回复

**Comment by hulianyuyy** [comment]
我的文件是UTF-8编码，但是我没有遇到你所说的错误。如果你持续遇到这一错误，你可以将103行的mode = ["dev", "test", "train"]分别改为mode = ["dev"]， mode = ["test"]和mode = ["train"]，然后分别更改成对应的编码方式运行生成文件和裁剪图片，来完成预处理过程。

**Comment by Uily1YUT** [comment]
好的，已解决。我重新检查了数据集里train的csv文件，删除异常符号之后，使用UTF-8可以编码
