### ISSUE TITLE
evaluate the pretrained model：IndexError: list index out of range

### ISSUE THREAD

**Issue by Lulo187** [hulianyuyy/CorrNet#53]
Thank you for your excellent work. I'm always encountering this issue when trying to evaluate the pretrained model. Could you please advise on how to resolve this issue?

.git does not exist in current dir
[ Fri May 17 11:05:48 2024 ] Model:   slr_network.SLRModel.
[ Fri May 17 11:05:48 2024 ] Weights: dev_18.90_PHOENIX14-T.pt.
  0%|                                                                                                                                     | 0/260 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 255, in <module>
    processor.start()
  File "main.py", line 97, in start
    dev_wer = seq_eval(self.arg, self.data_loader["dev"], self.model, self.device,
  File "/home/lulo/program/CorrNet-main/seq_scripts.py", line 58, in seq_eval
    for batch_idx, data in enumerate(tqdm(loader)):
  File "/home/lulo/anaconda3/envs/CorrNet/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/lulo/anaconda3/envs/CorrNet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/lulo/anaconda3/envs/CorrNet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/lulo/anaconda3/envs/CorrNet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/lulo/anaconda3/envs/CorrNet/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lulo/anaconda3/envs/CorrNet/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lulo/anaconda3/envs/CorrNet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lulo/anaconda3/envs/CorrNet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lulo/program/CorrNet-main/dataset/dataloader_video.py", line 50, in __getitem__
    input_data, label = self.normalize(input_data, label)
  File "/home/lulo/program/CorrNet-main/dataset/dataloader_video.py", line 87, in normalize
    video, label = self.data_aug(video, label, file_id)
  File "/home/lulo/program/CorrNet-main/utils/video_augmentation.py", line 24, in __call__
    image = t(image)
  File "/home/lulo/program/CorrNet-main/utils/video_augmentation.py", line 157, in __call__
    im_h, im_w, im_c = clip[0].shape
IndexError: list index out of range

**Comment by hulianyuyy** [comment]
You may refer to [this issue](https://github.com/hulianyuyy/CorrNet/issues/10#issuecomment-1660363025) to check if you have the same problem.
